apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-hello-pipeline
  namespace:  python-hello-build
spec:
  resources:
  - name: git-source-resource
    type: git
  - name: result-image
    type: image
  tasks:
    - name: generate-image-tag
      taskRef:
        name: generate-image-tag
      resources:
        outputs:
        - name: result-image
          resource: result-image
    - name: build-hello-python
      taskRef:
        name: build-hello-python
      params:
      - name: pathToDockerFile
        value: $(resources.inputs.git-resource.path)/source/Dockerfile
      - name: pathToContext
        value: $(resources.inputs.git-resource.path)/source
      - name: imageURL
        value: $(tasks.generate-image-tag.results.image-url)
      resources:
        inputs:
        - name: git-resource
          resource: git-source-resource
        outputs:
        - name: result-image
          resource: result-image
      